# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('equipment_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('equipment_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('MICROMETER', 'Micrometer'), ('CALIPER', 'Vernier / Digital Caliper'), ('DIAL_INDICATOR', 'Dial Indicator'), ('PRESSURE_GAUGE', 'Pressure Gauge'), ('SCALE', 'Weighing Scale'), ('TEMPERATURE', 'Temperature Sensor / Controller'), ('MULTIMETER', 'Multimeter'), ('TORQUE_WRENCH', 'Torque Wrench'), ('CMM', 'Coordinate Measuring Machine (CMM)'), ('OTHER', 'Other Measuring Device')], default='CALIPER', max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(help_text='Workshop, Lab, Line A, Tool Crib, etc.', max_length=150)),
                ('measurement_range', models.CharField(blank=True, help_text='e.g. 0 - 150 mm, 0 - 10 Bar', max_length=100)),
                ('accuracy', models.CharField(blank=True, help_text='e.g. +/- 0.02 mm, Class 1.0', max_length=100)),
                ('calibration_frequency_months', models.PositiveIntegerField(default=12, help_text='Calibration cycle in months')),
                ('last_calibration_date', models.DateField(default=django.utils.timezone.now)),
                ('next_calibration_date', models.DateField(blank=True, null=True)),
                ('calibration_provider', models.CharField(default='Internal Metrology Lab', max_length=150)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='calibration/certificates/%Y/%m/')),
                ('status', models.CharField(choices=[('VALID', 'Valid (In Tolerance)'), ('DUE_SOON', 'Calibration Due Soon'), ('EXPIRED', 'Calibration Expired'), ('OUT_OF_SERVICE', 'Out of Service')], db_index=True, default='VALID', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='departments.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['next_calibration_date', 'equipment_id'],
            },
        ),
    ]
