# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('departments', '0001_initial'),
        ('ncr', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('audit_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('audit_title', models.CharField(max_length=255)),
                ('audit_date', models.DateField()),
                ('scope', models.TextField(help_text='Boundary, processes, and shifts covered by this audit')),
                ('criteria', models.TextField(default='ISO 9001:2015, Quality Manual, Work Instructions')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('REPORTING', 'Reporting'), ('CLOSED', 'Closed')], db_index=True, default='SCHEDULED', max_length=30)),
                ('summary_notes', models.TextField(blank=True, help_text='Executive audit outcome summary')),
                ('audit_team', models.ManyToManyField(blank=True, related_name='participated_audits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='departments.department')),
                ('lead_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_audits', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='processes.process')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('finding_type', models.CharField(choices=[('MAJOR_NC', 'Major Nonconformity'), ('MINOR_NC', 'Minor Nonconformity'), ('OBSERVATION', 'Observation'), ('OFI', 'Opportunity For Improvement')], default='MINOR_NC', max_length=30)),
                ('description', models.TextField()),
                ('evidence', models.TextField()),
                ('clause', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='actions.action')),
                ('linked_ncr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='ncr.ncr')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_audit_findings', to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.auditplan')),
            ],
            options={
                'ordering': ['finding_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_clause', models.CharField(help_text='e.g. 7.1.5, 8.5.1, 9.2', max_length=50)),
                ('question', models.TextField()),
                ('requirement', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True, help_text='Sampled records, documents, observations')),
                ('result', models.CharField(choices=[('CONFORMITY', 'Conformity'), ('NONCONFORMITY', 'Nonconformity'), ('OBSERVATION', 'Observation'), ('OFI', 'Opportunity For Improvement')], default='CONFORMITY', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='audits.auditplan')),
            ],
            options={
                'ordering': ['iso_clause', 'id'],
            },
        ),
    ]
