# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementReviewMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField(default=django.utils.timezone.now)),
                ('participants', models.TextField(help_text='Names/Titles of attendees present')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('MINUTES_DRAFT', 'Minutes Draft'), ('MINUTES_APPROVED', 'Minutes Approved')], default='SCHEDULED', max_length=30)),
                ('general_summary', models.TextField(blank=True, help_text='Executive review overview and opening statement')),
                ('inputs_previous_actions', models.TextField(blank=True, verbose_name='Status of actions from previous management reviews')),
                ('inputs_audit_results', models.TextField(blank=True, verbose_name='Internal and external audit findings summary')),
                ('inputs_customer_feedback', models.TextField(blank=True, verbose_name='Customer satisfaction & feedback')),
                ('inputs_process_performance', models.TextField(blank=True, verbose_name='Process performance & conformity of products')),
                ('inputs_quality_objectives', models.TextField(blank=True, verbose_name='Extent to which quality objectives have been met')),
                ('inputs_ncr_capa_status', models.TextField(blank=True, verbose_name='Nonconformities and corrective actions status')),
                ('inputs_supplier_performance', models.TextField(blank=True, verbose_name='Performance of external providers and suppliers')),
                ('inputs_risks_opportunities', models.TextField(blank=True, verbose_name='Effectiveness of actions taken to address risks & opportunities')),
                ('inputs_resource_needs', models.TextField(blank=True, verbose_name='Adequacy of resources')),
                ('inputs_improvement_opportunities', models.TextField(blank=True, verbose_name='Opportunities for continual improvement')),
                ('outputs_decisions', models.TextField(blank=True, verbose_name='Decisions related to opportunities for improvement')),
                ('outputs_resource_requirements', models.TextField(blank=True, verbose_name='Resource needs decided')),
                ('outputs_improvement_projects', models.TextField(blank=True, verbose_name='Quality management system change decisions')),
                ('chairperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaired_reviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date', '-id'],
            },
        ),
    ]
