# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Apex Precision Engineering Ltd. (QMS Hub)', max_length=150)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('ncr_prefix', models.CharField(default='NCR', max_length=10)),
                ('capa_prefix', models.CharField(default='CAPA', max_length=10)),
                ('action_prefix', models.CharField(default='ACT', max_length=10)),
                ('audit_prefix', models.CharField(default='AUD', max_length=10)),
                ('notification_days_before', models.PositiveIntegerField(default=7, help_text='Days before due date to send alert')),
                ('calibration_alert_days', models.PositiveIntegerField(default=30, help_text='Days before calibration expiry to alert')),
                ('risk_high_threshold', models.PositiveIntegerField(default=10)),
                ('risk_critical_threshold', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CLOSE', 'Close'), ('REOPEN', 'Reopen'), ('LOGIN', 'Login')], max_length=20)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.CharField(db_index=True, max_length=100)),
                ('record_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
