# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('risk_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the risk event')),
                ('cause', models.TextField(help_text='Root causes or vulnerability factors')),
                ('potential_consequence', models.TextField(help_text='Impact on product quality, customer or compliance')),
                ('existing_control', models.TextField(blank=True, help_text='Current preventive or detective controls')),
                ('likelihood', models.IntegerField(choices=[(1, '1 - Very Rare'), (2, '2 - Rare'), (3, '3 - Moderate'), (4, '4 - Likely'), (5, '5 - Very Frequent')], default=3)),
                ('severity', models.IntegerField(choices=[(1, '1 - Negligible'), (2, '2 - Minor'), (3, '3 - Moderate'), (4, '4 - Critical'), (5, '5 - Catastrophic')], default=3)),
                ('risk_score', models.IntegerField(default=9, editable=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', editable=False, max_length=20)),
                ('action_required', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATING', 'Mitigation In Progress'), ('CONTROLLED', 'Controlled'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('effectiveness', models.TextField(blank=True, help_text='Review of residual risk effectiveness')),
                ('evidence', models.TextField(blank=True, help_text='Evidence of mitigation implementation')),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='departments.department')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='processes.process')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_risks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-risk_score', 'risk_id'],
            },
        ),
    ]
