# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ncr', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('product', models.CharField(max_length=150)),
                ('batch_lot', models.CharField(max_length=100)),
                ('machine', models.CharField(help_text='Machine ID / Line number', max_length=100)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning Shift (1st)'), ('AFTERNOON', 'Afternoon Shift (2nd)'), ('NIGHT', 'Night Shift (3rd)')], default='MORNING', max_length=20)),
                ('overall_result', models.CharField(choices=[('OK', 'Conforming (OK)'), ('NG', 'Nonconforming (NG)'), ('PENDING', 'Pending Inspection')], db_index=True, default='OK', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('linked_ncr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='ncr.ncr')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='processes.process')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_name', models.CharField(help_text='e.g. Outer Diameter, Surface Finish, Torque', max_length=150)),
                ('specification', models.CharField(help_text='e.g. 50.00 +/- 0.02 mm, Ra <= 0.8', max_length=150)),
                ('measured_value', models.CharField(help_text='Actual measured value or observed state', max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('result', models.CharField(choices=[('OK', 'OK'), ('NG', 'NG (No Good)'), ('NA', 'N/A')], default='OK', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspections/photos/%Y/%m/')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
