# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('inputs', models.TextField(blank=True, help_text='Inputs to the process (e.g. raw material, engineering drawings)')),
                ('outputs', models.TextField(blank=True, help_text='Outputs from the process (e.g. machined parts, inspection certificates)')),
                ('equipment', models.TextField(blank=True, help_text='Major equipment involved (e.g. 5-Axis CNC Mill)')),
                ('tools', models.TextField(blank=True, help_text='Tools and fixtures required')),
                ('parameters', models.TextField(blank=True, help_text='Critical process parameters (e.g. Feed rate, Spindle speed, Temperature)')),
                ('inspection_points', models.TextField(blank=True, help_text='In-process and final inspection checkpoints')),
                ('quality_gates', models.TextField(blank=True, help_text='Quality gates required before handoff')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='departments.department')),
                ('process_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_processes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Processes',
                'ordering': ['code'],
            },
        ),
    ]
