# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ncr_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('product', models.CharField(help_text='Part name or product description', max_length=150)),
                ('batch_lot', models.CharField(help_text='Batch or Lot Number', max_length=100)),
                ('source', models.CharField(choices=[('INTERNAL_AUDIT', 'Internal Audit'), ('EXTERNAL_AUDIT', 'External Audit'), ('INSPECTION', 'Shop Floor Inspection'), ('PRODUCTION', 'Production Routine'), ('CUSTOMER_COMPLAINT', 'Customer Complaint'), ('SUPPLIER', 'Supplier / Incoming'), ('MANAGEMENT_REVIEW', 'Management Review'), ('OTHER', 'Other')], default='PRODUCTION', max_length=30)),
                ('description', models.TextField(help_text='Clear description of the nonconformity')),
                ('requirement', models.TextField(help_text='Standard, drawing tolerance, or procedure requirement violated')),
                ('evidence', models.TextField(blank=True, help_text='Evidence observed or measured data')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='ncr/evidence/%Y/%m/')),
                ('classification', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MINOR', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('immediate_correction', models.TextField(blank=True, help_text='Immediate fix applied to affected parts (quarantine, rework, scrap)')),
                ('containment_action', models.TextField(blank=True, help_text='Action to prevent affected material from escaping to customer or downstream')),
                ('root_cause_summary', models.TextField(blank=True, help_text='Final root cause conclusion')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONTAINMENT', 'Containment'), ('RCA', 'Root Cause Analysis'), ('CORRECTIVE_ACTION', 'Corrective Action'), ('VERIFICATION', 'Verification'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30)),
                ('verification_notes', models.TextField(blank=True, help_text='QA sign-off and verification results')),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='departments.department')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='processes.process')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_ncrs', to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_ncrs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ncrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nonconformity Report',
                'verbose_name_plural': 'Nonconformity Reports',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FiveWhysAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('why_1', models.TextField(blank=True, verbose_name='1. Why did the issue occur?')),
                ('why_2', models.TextField(blank=True, verbose_name='2. Why?')),
                ('why_3', models.TextField(blank=True, verbose_name='3. Why?')),
                ('why_4', models.TextField(blank=True, verbose_name='4. Why?')),
                ('why_5', models.TextField(blank=True, verbose_name='5. Why? (Root Cause)')),
                ('root_cause_conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ncr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='five_whys', to='ncr.ncr')),
            ],
        ),
        migrations.CreateModel(
            name='FishboneCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MAN', 'Man (People / Operator)'), ('MACHINE', 'Machine (Equipment / Tooling)'), ('METHOD', 'Method (Procedures / Process)'), ('MATERIAL', 'Material (Raw Material / Parts)'), ('MEASUREMENT', 'Measurement (Inspection / Gage)'), ('ENVIRONMENT', 'Environment (Workplace / Temperature)')], max_length=20)),
                ('cause_description', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this confirmed as a key root cause?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ncr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishbone_causes', to='ncr.ncr')),
            ],
            options={
                'ordering': ['category', '-is_primary', 'id'],
            },
        ),
    ]
