# Generated by Django 6.1.1 on 2026-09-13 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncr', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncr',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs', to='processes.process'),
        ),
    ]
