# Generated by Django 6.1.1 on 2026-09-13 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('ncr', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('capa_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('NCR', 'Nonconformity Report (NCR)'), ('AUDIT', 'Audit Finding'), ('RISK', 'Risk Assessment'), ('CUSTOMER', 'Customer Complaint'), ('MANAGEMENT_REVIEW', 'Management Review'), ('RECURRENT_ISSUE', 'Recurrent Process Deviation')], default='NCR', max_length=30)),
                ('description', models.TextField(help_text='Detailed problem description and background')),
                ('root_cause', models.TextField(help_text='Underlying systemic root cause')),
                ('corrective_action', models.TextField(help_text='Action to eliminate the cause of existing nonconformity')),
                ('preventive_action', models.TextField(help_text='Action to eliminate causes of potential nonconformities across processes')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('verification_method', models.CharField(help_text='Method used to verify implementation & effectiveness', max_length=255)),
                ('effectiveness_result', models.TextField(blank=True, help_text='Evidence and metrics proving non-recurrence')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ANALYSIS', 'Root Cause Analysis'), ('IMPLEMENTATION', 'Implementation'), ('VERIFICATION', 'Verification'), ('EFFECTIVENESS_CHECK', 'Effectiveness Check'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30)),
                ('evidence', models.TextField(blank=True, help_text='Summary of supporting implementation evidence')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='capa/evidence/%Y/%m/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('related_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='audits.auditfinding')),
                ('related_ncr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='ncr.ncr')),
                ('related_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='risks.risk')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_capas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_capas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
